name: create a comment on new issues

on:
 issues:
  types: [opened]

jobs:
  comment-with-action:
   runs-on: ubuntu-latest
   steps:
    - name: "github dump context"
      run: echo '${{ toJSON(github.event) }}' | jq
      shell: bash
 
